<Workspace Version="0.8.2.2392" X="698.620264960704" Y="-0.973717908453409" zoom="0.700092700513465" Name="Home" Description="" RunType="Manual" RunPeriod="100" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DoubleInput guid="ad24636f-5e15-4b2e-820f-d481cd4ed22b" type="Dynamo.Nodes.DoubleInput" nickname="Number" x="-688.896257978466" y="426.667912226822" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Double value="5" />
    </Dynamo.Nodes.DoubleInput>
    <Dynamo.Nodes.DSModelElementSelection guid="24039b82-a5c2-4c7b-87e4-40c7d19ce1f6" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-602.578352109254" y="636.203587444605" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <instance id="730cd6f2-40a1-43dc-8485-13fa6e041589-0003ffe3" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSFunction guid="9f8b5ff9-1b83-48e4-b8f4-e44426429f71" type="Dynamo.Nodes.DSFunction" nickname="Element.Id" x="-346.195173062699" y="636.973687701228" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.Id" />
    <Dynamo.Nodes.DSFunction guid="193d4300-7f5c-4604-9897-ecc1feddc989" type="Dynamo.Nodes.DSFunction" nickname="RebarContainer.ByCurve" x="245.122702698244" y="585.023888010616" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="..\..\bin\AnyCPU\Debug\DynamoRebar.dll" function="Revit.Elements.RebarContainer.ByCurve@Autodesk.DesignScript.Geometry.Curve[],int,string,Revit.Elements.Element,string,string,Revit.Elements.Element,Revit.Elements.Element" />
    <Dynamo.Nodes.DSFunction guid="b9527c1d-3472-4724-a37e-f5595741b05c" type="Dynamo.Nodes.DSFunction" nickname="Rebar.Morphed" x="-323.562261866448" y="284.596803057568" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="..\..\bin\AnyCPU\Debug\DynamoRebar.dll" function="DynamoRebar.Rebar.Morphed@Autodesk.DesignScript.Geometry.Curve,Autodesk.DesignScript.Geometry.Curve,int,double">
      <PortInfo index="3" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSEdgeSelection guid="b6126bb4-40c0-4009-aeaf-c426c326c06e" type="Dynamo.Nodes.DSEdgeSelection" nickname="Select Edge" x="-753.468983947686" y="311.748806557436" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <instance id="8b22563e-3247-4edd-977a-41f9118db6db-000334bc:0:INSTANCE:8b22563e-3247-4edd-977a-41f9118db6db-000334ab:90:LINEAR" />
    </Dynamo.Nodes.DSEdgeSelection>
    <Dynamo.Nodes.DSEdgeSelection guid="9dbd0911-c0d0-4051-abd2-e27e6d3b1354" type="Dynamo.Nodes.DSEdgeSelection" nickname="Select Edge" x="-759.502762503212" y="222.750572863425" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <instance id="8b22563e-3247-4edd-977a-41f9118db6db-000334bc:0:INSTANCE:8b22563e-3247-4edd-977a-41f9118db6db-000334ab:88:LINEAR" />
    </Dynamo.Nodes.DSEdgeSelection>
    <DynamoRebarUI.RebarBarType guid="818c65b8-8d3c-4607-b377-8341b97971c3" type="DynamoRebarUI.RebarBarType" nickname="Rebar Bar Type" x="-456.980218579281" y="916.970634583498" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" index="1:#11" />
    <DynamoRebarUI.RebarHookOrientation guid="ea4d9ae8-daac-4bf8-ad91-af1310f8927d" type="DynamoRebarUI.RebarHookOrientation" nickname="Rebar Hook Orientation" x="-507.980218579281" y="1018.38577567542" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" index="0:Left" />
    <DynamoRebarUI.RevitRebarHookType guid="d833f208-9560-4440-b70a-09bcc1bfdc04" type="DynamoRebarUI.RevitRebarHookType" nickname="Rebar Hook Type" x="-467.980218579281" y="1106.94547634725" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" index="0:Rebar Hook 90" />
    <DynamoRebarUI.RebarStyle guid="242c2c29-c078-486f-94e8-4839a933c912" type="DynamoRebarUI.RebarStyle" nickname="Rebar Style" x="-431.980218579281" y="828.410933911676" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" index="0:Standard" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="ad24636f-5e15-4b2e-820f-d481cd4ed22b" start_index="0" end="b9527c1d-3472-4724-a37e-f5595741b05c" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="24039b82-a5c2-4c7b-87e4-40c7d19ce1f6" start_index="0" end="9f8b5ff9-1b83-48e4-b8f4-e44426429f71" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9f8b5ff9-1b83-48e4-b8f4-e44426429f71" start_index="0" end="193d4300-7f5c-4604-9897-ecc1feddc989" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="b9527c1d-3472-4724-a37e-f5595741b05c" start_index="0" end="193d4300-7f5c-4604-9897-ecc1feddc989" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b6126bb4-40c0-4009-aeaf-c426c326c06e" start_index="0" end="b9527c1d-3472-4724-a37e-f5595741b05c" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="9dbd0911-c0d0-4051-abd2-e27e6d3b1354" start_index="0" end="b9527c1d-3472-4724-a37e-f5595741b05c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="818c65b8-8d3c-4607-b377-8341b97971c3" start_index="0" end="193d4300-7f5c-4604-9897-ecc1feddc989" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="ea4d9ae8-daac-4bf8-ad91-af1310f8927d" start_index="0" end="193d4300-7f5c-4604-9897-ecc1feddc989" end_index="4" portType="0" />
    <Dynamo.Models.ConnectorModel start="ea4d9ae8-daac-4bf8-ad91-af1310f8927d" start_index="0" end="193d4300-7f5c-4604-9897-ecc1feddc989" end_index="5" portType="0" />
    <Dynamo.Models.ConnectorModel start="d833f208-9560-4440-b70a-09bcc1bfdc04" start_index="0" end="193d4300-7f5c-4604-9897-ecc1feddc989" end_index="6" portType="0" />
    <Dynamo.Models.ConnectorModel start="d833f208-9560-4440-b70a-09bcc1bfdc04" start_index="0" end="193d4300-7f5c-4604-9897-ecc1feddc989" end_index="7" portType="0" />
    <Dynamo.Models.ConnectorModel start="242c2c29-c078-486f-94e8-4839a933c912" start_index="0" end="193d4300-7f5c-4604-9897-ecc1feddc989" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Models.AnnotationModel guid="ffa653b0-b52d-4e9f-bb3f-2133c164ef8b" annotationText="Host Element" left="-612.578352109254" top="606.203587444605" width="406.383179046555" height="123.770100256623" fontSize="14" InitialTop="636.203587444605" InitialHeight="125.278544895504" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="24039b82-a5c2-4c7b-87e4-40c7d19ce1f6" />
      <Models ModelGuid="9f8b5ff9-1b83-48e4-b8f4-e44426429f71" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="ada3c575-f5fd-4c02-87a6-0b79c12ec4df" annotationText="Curvature" left="-769.502762503212" top="192.750572863425" width="668.940500636764" height="301.917339363397" fontSize="14" InitialTop="222.750572863425" InitialHeight="313.348219913687" TextblockHeight="20" backgrouund="#FFA4E1FF">
      <Models ModelGuid="ad24636f-5e15-4b2e-820f-d481cd4ed22b" />
      <Models ModelGuid="9dbd0911-c0d0-4051-abd2-e27e6d3b1354" />
      <Models ModelGuid="b6126bb4-40c0-4009-aeaf-c426c326c06e" />
      <Models ModelGuid="b9527c1d-3472-4724-a37e-f5595741b05c" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="2b8b8ad6-775f-488d-a90f-54edfc92bb73" annotationText="Rebar Options&#xD;&#xA;" left="-517.980218579281" top="784.410933911676" width="276" height="415.534542435569" fontSize="14" InitialTop="828.410933911676" InitialHeight="380.108808402064" TextblockHeight="34" backgrouund="#FFFFC999">
      <Models ModelGuid="818c65b8-8d3c-4607-b377-8341b97971c3" />
      <Models ModelGuid="ea4d9ae8-daac-4bf8-ad91-af1310f8927d" />
      <Models ModelGuid="d833f208-9560-4440-b70a-09bcc1bfdc04" />
      <Models ModelGuid="242c2c29-c078-486f-94e8-4839a933c912" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>